/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface CompoundInterface extends Interface {
  functions: {
    sum: TypedFunctionDescription<{
      encode([a, b]: [BigNumberish, BigNumberish]): string;
    }>;
  };

  events: {};
}

export class Compound extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Compound;
  attach(addressOrName: string): Compound;
  deployed(): Promise<Compound>;

  on(event: EventFilter | string, listener: Listener): Compound;
  once(event: EventFilter | string, listener: Listener): Compound;
  addListener(eventName: EventFilter | string, listener: Listener): Compound;
  removeAllListeners(eventName: EventFilter | string): Compound;
  removeListener(eventName: any, listener: Listener): Compound;

  interface: CompoundInterface;

  functions: {
    sum(a: BigNumberish, b: BigNumberish): Promise<BigNumber>;
  };

  sum(a: BigNumberish, b: BigNumberish): Promise<BigNumber>;

  filters: {};

  estimate: {
    sum(a: BigNumberish, b: BigNumberish): Promise<BigNumber>;
  };
}
