/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface LTCRInterface extends Interface {
  functions: {
    curate: TypedFunctionDescription<{ encode([]: []): string }>;

    getReward: TypedFunctionDescription<{
      encode([action]: [BigNumberish]): string;
    }>;

    getAssignment: TypedFunctionDescription<{
      encode([agent]: [string]): string;
    }>;

    registerAgent: TypedFunctionDescription<{
      encode([agent, collateral]: [string, BigNumberish]): string;
    }>;

    setCollateral: TypedFunctionDescription<{
      encode([mincollateral]: [BigNumberish]): string;
    }>;

    setFactor: TypedFunctionDescription<{
      encode([layer, factor]: [BigNumberish, BigNumberish]): string;
    }>;

    renounceOwnership: TypedFunctionDescription<{ encode([]: []): string }>;

    owner: TypedFunctionDescription<{ encode([]: []): string }>;

    isOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    setBounds: TypedFunctionDescription<{
      encode([layer, lower, upper]: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    getAgentFactor: TypedFunctionDescription<{
      encode([agent]: [string]): string;
    }>;

    update: TypedFunctionDescription<{
      encode([agent, action]: [string, BigNumberish]): string;
    }>;

    setReward: TypedFunctionDescription<{
      encode([action, reward]: [BigNumberish, BigNumberish]): string;
    }>;

    setLayers: TypedFunctionDescription<{
      encode([layers]: [BigNumberish[]]): string;
    }>;

    getBounds: TypedFunctionDescription<{
      encode([layer]: [BigNumberish]): string;
    }>;

    getLayers: TypedFunctionDescription<{ encode([]: []): string }>;

    getAgentCollateral: TypedFunctionDescription<{
      encode([agent]: [string]): string;
    }>;

    initialize: TypedFunctionDescription<{
      encode([sender]: [string]): string;
    }>;

    getScore: TypedFunctionDescription<{ encode([agent]: [string]): string }>;

    getFactor: TypedFunctionDescription<{
      encode([layer]: [BigNumberish]): string;
    }>;

    transferOwnership: TypedFunctionDescription<{
      encode([newOwner]: [string]): string;
    }>;
  };

  events: {
    NewBound: TypedEventDescription<{
      encodeTopics([lower, upper]: [null, null]): string[];
    }>;

    RegisterAgent: TypedEventDescription<{
      encodeTopics([agent, collateral]: [null, null]): string[];
    }>;

    Update: TypedEventDescription<{
      encodeTopics([agent, reward, score]: [null, null, null]): string[];
    }>;

    Curate: TypedEventDescription<{
      encodeTopics([round, start, end]: [null, null, null]): string[];
    }>;

    OwnershipTransferred: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;
  };
}

export class LTCR extends Contract {
  connect(signerOrProvider: Signer | Provider | string): LTCR;
  attach(addressOrName: string): LTCR;
  deployed(): Promise<LTCR>;

  on(event: EventFilter | string, listener: Listener): LTCR;
  once(event: EventFilter | string, listener: Listener): LTCR;
  addListener(eventName: EventFilter | string, listener: Listener): LTCR;
  removeAllListeners(eventName: EventFilter | string): LTCR;
  removeListener(eventName: any, listener: Listener): LTCR;

  interface: LTCRInterface;

  functions: {
    curate(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    getReward(action: BigNumberish): Promise<BigNumber>;

    getAssignment(agent: string): Promise<number>;

    registerAgent(
      agent: string,
      collateral: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setCollateral(
      mincollateral: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setFactor(
      layer: BigNumberish,
      factor: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    owner(): Promise<string>;

    isOwner(): Promise<boolean>;

    setBounds(
      layer: BigNumberish,
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getAgentFactor(agent: string): Promise<BigNumber>;

    update(
      agent: string,
      action: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setReward(
      action: BigNumberish,
      reward: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setLayers(
      layers: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getBounds(
      layer: BigNumberish
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
    }>;

    getLayers(): Promise<number[]>;

    getAgentCollateral(agent: string): Promise<BigNumber>;

    initialize(
      sender: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getScore(agent: string): Promise<BigNumber>;

    getFactor(layer: BigNumberish): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  curate(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  getReward(action: BigNumberish): Promise<BigNumber>;

  getAssignment(agent: string): Promise<number>;

  registerAgent(
    agent: string,
    collateral: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setCollateral(
    mincollateral: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setFactor(
    layer: BigNumberish,
    factor: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  owner(): Promise<string>;

  isOwner(): Promise<boolean>;

  setBounds(
    layer: BigNumberish,
    lower: BigNumberish,
    upper: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getAgentFactor(agent: string): Promise<BigNumber>;

  update(
    agent: string,
    action: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setReward(
    action: BigNumberish,
    reward: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setLayers(
    layers: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getBounds(
    layer: BigNumberish
  ): Promise<{
    0: BigNumber;
    1: BigNumber;
  }>;

  getLayers(): Promise<number[]>;

  getAgentCollateral(agent: string): Promise<BigNumber>;

  initialize(
    sender: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getScore(agent: string): Promise<BigNumber>;

  getFactor(layer: BigNumberish): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    NewBound(lower: null, upper: null): EventFilter;

    RegisterAgent(agent: null, collateral: null): EventFilter;

    Update(agent: null, reward: null, score: null): EventFilter;

    Curate(round: null, start: null, end: null): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimate: {
    curate(): Promise<BigNumber>;

    getReward(action: BigNumberish): Promise<BigNumber>;

    getAssignment(agent: string): Promise<BigNumber>;

    registerAgent(agent: string, collateral: BigNumberish): Promise<BigNumber>;

    setCollateral(mincollateral: BigNumberish): Promise<BigNumber>;

    setFactor(layer: BigNumberish, factor: BigNumberish): Promise<BigNumber>;

    renounceOwnership(): Promise<BigNumber>;

    owner(): Promise<BigNumber>;

    isOwner(): Promise<BigNumber>;

    setBounds(
      layer: BigNumberish,
      lower: BigNumberish,
      upper: BigNumberish
    ): Promise<BigNumber>;

    getAgentFactor(agent: string): Promise<BigNumber>;

    update(agent: string, action: BigNumberish): Promise<BigNumber>;

    setReward(action: BigNumberish, reward: BigNumberish): Promise<BigNumber>;

    setLayers(layers: BigNumberish[]): Promise<BigNumber>;

    getBounds(layer: BigNumberish): Promise<BigNumber>;

    getLayers(): Promise<BigNumber>;

    getAgentCollateral(agent: string): Promise<BigNumber>;

    initialize(sender: string): Promise<BigNumber>;

    getScore(agent: string): Promise<BigNumber>;

    getFactor(layer: BigNumberish): Promise<BigNumber>;

    transferOwnership(newOwner: string): Promise<BigNumber>;
  };
}
